dist: xenial
branches:
  except:
    - gh-pages
addons:
  firefox: latest
  apt:
    packages:
    - doxygen
cache:
  directories:
    - node_modules
before_install:
- export TZ=CST6CDT
- npm install npm@latest -g
- node -v
- npm -v
- python -V
- pip -V
- firefox -v
- doxygen --version
install:
- npm install
- pip install --user tox
- nohup npm run httpbin &
- gcc -v
- git clone https://github.com/juj/emsdk.git
- (cd emsdk && git checkout 9538381d56272818cba77a808ba46fdac6c961c8)
- emsdk/emsdk install sdk-1.38.30-64bit
- emsdk/emsdk activate sdk-1.38.30-64bit
- cat ~/.emscripten
- (source emsdk/emsdk_env.sh && emcc -v)
before_script:
- while ! nc -q 1 127.0.0.1 64526 </dev/null; do sleep 2; done
- curl http://127.0.0.1:64526/get?show_env=1
- make lint
- npm run lint
- make native
- make unittest
- (source emsdk/emsdk_env.sh && make vjs)
- (source emsdk/emsdk_env.sh && make vjs BUILD=debug)
- (source emsdk/emsdk_env.sh && make vjs BUILD=profile)
- (source emsdk/emsdk_env.sh && make vjs BUILD=release TARGET=asmjs-unknown-emscripten)
- tar -tf $(npm pack)
script:
- make testjs
- make testnative
- make testhttpbin
- npm run test-min
- npm run test-asmjs
before_deploy:
- npm run doxygen
- export ESH_64_RELEASE="esh_"$TRAVIS_TAG"_x86_64-unknown-linux-gnu_release.zip"
- zip -j $ESH_64_RELEASE dist/esh README.md LICENSE.txt
deploy:
  - provider: npm
    skip_cleanup: true
    email: webapps.ops@ni.com
    api_key:
        secure: u479lyoasPF36OYHjloChj/zphXM7jcwWvZzuqF1jnMN5lkeYQ1tDA7e6hydeBUbmHrQgqh0GsablAK0ZZfnQt6CTw9qsDiAk2SnkbqRbbA3cxrQED24ev80UzyNfOeh90wP53hc2dBw1boaDyoLy0Sl0Dq+Dc91O/zfNgCKZFZneW3kvb8AOT0NHcfL4bFwc1kjMF1uBazfozEXved2+yOICU/voHYx7OfVZWWTf0p7KEEnJ/pP4ibkD3eti5L2zm3/RUj+awXlSVmqLnhjn9XjWgc9Vb5AdY68iX3NL8Gri/01sFLVa6+Nt8I1dlqQLc7KLIMw0tPtKQrn3Atr3c/8hJsQpDEzNspU+L+vYuYpBHA5QuDyiPGFdXH/unkKQ7vCBBqSMEoYtEiCX35ukfI/62pdq8biXlEP9vRBN4M99UJ6/ezKweC8wOXOheeCjvYV0YOljiiaisaS+t97cwqCQLITPYKoC4Nli9JiSV7+ZH6PSue5IjwPXgAV7Dg+wxvm1uojw/1aclja8W8ATmDZFjJiaqwaY2a6L54vnE9BLectrbpdtvc7YmGbnGPA2gmTRJkKhZQ/1hlUzpGZ7fvzGaHaY1912scPrFytB3mOio7HtKUR7EqM6ryLmwyIPn8+cFdEkAHb/t9FqGLNVGNBExT7moaLo6oeldcFFx4=
    on:
      tags: true
      repo: ni/VireoSDK
  - provider: pages
    skip_cleanup: true
    keep-history: true
    local_dir: gh-pages/
    email: vireobot@users.noreply.github.com
    name: Vireo Bot
    github_token:
      secure: PJD/9XrPDUATO1O5SZXSosi0maiSFh4YblSOGhbcNacJmuWGYTpRSdXS+uEGI7vtegFrfl7Yo2AoyVZ4shKArjwbVSjUOyBPphXJfRV/8nV7I90d+mvJ8xR4F/2CED1ddHAbnsHVzluXCus8L1Mr6CVrO2qURlZ6SG6BR0jn6hfOR93VzEotmHbF32Pm+MpQWMcDOch1lUkEy4+u96LcfhA6qlQEVH6/MJs3o+sDqe4LlAY6SGKAq6rzwG3w5ZmGQENN+1cXYy7fQz2gNzro3UW59RoWzYECl7DApkM00LbhHu/i0xtDhrZpJV8sdCb2dgbe2HreT2egKdwT02uhotg9Z/mgEf2Com5B8hZlXSf8RbiGmaRHm/s1xv7jmjbDbrStnoPwH7zH8W9DTq2l8EpeueWyNhbx0q6inmi2ZgWgHpo9bk2Cb7gPXKV50WWjzq8ldzCbbBvKP11jKZhsADu0tDuakZpLLiNeDQN0a1/qkOl9AFSrqYe5imaVxAdM6andvH94sume5X5taBppDG9Apu0sfiM6fqrsph1fJM+cjIuwOXDI2OlQIZeQtHSEH7uj1B0FraZ/rLBY28tmlLQw9IbulmlhBrhwyehVZNP/3F0pDvy2FQrkLG30kkBu9fenREZI4w2Hy6l1HmblMhcSzABRJG3LhJKBjR9FzPQ=
    on: 
      tags: true
      repo: ni/VireoSDK
  - provider: releases
    overwrite: true
    skip_cleanup: true
    file:
      - $ESH_64_RELEASE
    on:
      tags: true
      repo: ni/VireoSDK
    api_key:
      secure: fMjCwcnQ0mPHXqeCBXAv/XeymPjGTH/EiX/g0MOikDwrPDwlRFOjTZRuOxcluPYilQTEWzTCiuyvkhA4dWmWVcnXU4CjxJBlkdbjTeut1Z3p3O62gp+x1qUnqMiJTsGU8+y8MRg25BCtM7XxdDr/7D8J1OT65HNh2hIS0nzCEG5ZYpSKSjv/tJvaz9gYCB3HF4klIcVBrO+2wjVVvVpkCqIHR44LqEAzqUm79x+CtutnTBfc7dvvMh5OrB7K1QivaCqJnmnaOGEaGL5zRNgikGG0xh6j44oj3hDNT0PHPGbBq+u205hqeP/LBK5IzTZqgoYWs5wV1q4B9gwMd0nJsEVldB+ICUEJxyc1NQtdrO4i/hNts4uv4WEzGRjCkGjvlRc512caAB8RImDbS9JJSE0fFNc+hQKOeBe30WgdlBjxsSqQZSlmuE1ssHxooqbLo7ahf1n851f3Ov3jjSpYxX2pRy+2lHoPzCs/uUkzNKofB2YtlpYpAvtyox2+khvI5DdSUkqUDqttsAsujS58JKQ9qoHMEXJbpIBsoQ9eeY4QXc7ihKuQa7RkFDeSS65FZ9colOHO9+4AcGgGolghFNcGkQaf1S3LU9xDgUb9cwSUOvGKYyzmIPlOE/ObXpPyfJt7WEfyJ3OxMO1gS5Sy4P6KNgxX+Thohdukrm3Es5s=
after_script:
- jobs -l
- kill $!
- cat ./nohup.out
